spring:
  application:
    name: ptm-p-k
  threads:
    virtual:
      enabled: true
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1
      credentials:
        access-key: noop
        secret-key: noop
    stream:
      bindings:
        produceOrder-out-0:
          destination: ptm-kinesis-stream
          content-type: application/json
      kinesis:
        binder:
          kpl-kcl-enabled: true
    function:
      definition: produceOrder
  output:
    ansi:
      enabled: always
  
